[name_pool]
family_names = [
  "김",
  "이",
  "박",
  "최",
  "정",
  "강",
  "조",
  "윤",
  "장",
  "임",
  "한",
  "오",
  "서",
  "신",
  "권",
]
given_names = [
  "민준",
  "서준",
  "도윤",
  "예준",
  "시우",
  "주원",
  "하준",
  "지호",
  "지후",
  "준우",
  "현우",
  "도현",
  "지훈",
  "우진",
  "민재",
  "서연",
  "서윤",
  "지우",
  "하윤",
  "지민",
  "수아",
  "지아",
  "유진",
  "채원",
  "윤서",
  "다은",
  "예은",
  "수빈",
  "소율",
  "지원",
]
